---
# tasks file for mssql
- name: add yum repository packages-microsoft-com-mssql-server-2017
  yum_repository:
    name: "{{ item.name }}"
    baseurl: "{{ item.baseurl }}"
    description: "{{ item.description }}"
    gpgkey: "{{ mssql_gpgkey }}"
    gpgcheck: yes
  when:
    - ansible_distribution == "CentOS" or ansible_distribution == "Red Hat Enterprise Linux" or ansible_distribution == "Fedora"
    - mssql_add_repositories == "yes"
  with_items: "{{ mssql_rhel_repositories }}"

- name: add zypper repository packages-microsoft-com-mssql-server-2017
  zypper_repository:
    name: "{{ item.name }}"
    repo: "{{ item.repo }}"
    auto_import_keys: yes
  when:
    - ansible_distribution == "openSUSE Leap"
    - mssql_add_repositories == "yes"
  with_items: "{{ mssql_opensuse_repositories }}"

- name: add apt key
  apt_key:
    url: "{{ mssql_gpgkey }}"
  when:
    - ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
    - mssql_add_repositories == "yes"

- name: add apt repository packages-microsoft-com-mssql-server-2017
  apt_repository:
    repo: deb [arch=amd64] "{{ item.repo }}" xenial main
  when:
    - ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
    - mssql_add_repositories == "yes"
  with_items: "{{ mssql_ubuntu_repositories }}"

- name: install software mssql-server (package)
  package:
    name: "{{ mssql_server_package[ansible_distribution] }}"
  environment:
    ACCEPT_EULA: Y
  when:
    - ansible_distribution != "Ubuntu"
  notify:
    - stop mssql-server
    - configure mssql-server using mssql-conf

- name: flush handlers
  meta: flush_handlers

- name: install software in mssql-server (apt)
  apt:
    name: "{{ mssql_server_package[ansible_distribution] }}"
    allow_unauthenticated: yes
  environment:
    ACCEPT_EULA: Y
  when:
    - ansible_distribution == "Ubuntu"
  notify:
    - configure mssql-server using mssql-conf

- name: install software mssql-tools (package)
  package:
    name: mssql-tools
  environment:
    ACCEPT_EULA: Y
  when:
    - ansible_distribution != "Ubuntu"

- name: install software in mssql-tools (apt)
  apt:
    name: mssql-tools
    allow_unauthenticated: yes
  environment:
    ACCEPT_EULA: Y
  when:
    - ansible_distribution == "Ubuntu"

- name: install software mssql-server-agent (package)
  package:
    name: "{{ mssql_server_agent_package[ansible_distribution] }}"
  environment:
    ACCEPT_EULA: Y
  when:
    - ansible_distribution != "Ubuntu"
  notify:
    - restart mssql-server

# - name: install software in mssql-server-agent (apt)
#   apt:
#     name: "{{ mssql_server_agent_package[ansible_distribution] }}"
#     allow_unauthenticated: yes
#   environment:
#     ACCEPT_EULA: Y
#   when:
#     - ansible_distribution == "Ubuntu"
#   notify:
#     - restart mssql-server

#- name: flush handlers
#  meta: flush_handlers

- name: start and enable mssql-server
  service:
    name: mssql-server
    state: started
    enabled: yes
  environment:
    ACCEPT_EULA: Y
  when:
    - ansible_virtualization_type != "docker"
