---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: libvirt
lint:
  name: yamllint
platforms:
  - name: mssql-centos-7
    box: centos/7
    memory: 4096
  - name: mssql-ubuntu-xenial
    box: ubuntu/xenial64
    memory: 4096
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: vagrant
verifier:
  name: goss
  lint:
    name: yamllint
