---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: mssql-centos-7
    image: centos:7
  - name: mssql-opensuse-42.3
    image: opensuse:42.3
  - name: mssql-ubuntu-xenial
    image: ubuntu:xenial
  - name: mssql-ubuntu-artful
    image: ubuntu:artful
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: goss
  lint:
    name: yamllint
