---

- name: Install IIS
  win_feature:
    name: Web-Server
    state: present
    include_sub_features: yes
    include_management_tools: yes

- name: Remove Default Web Site
  win_iis_website:
    name: "Default Web Site"
    state: absent

...